name: Build and push Docker images
description: "Build and push Docker images"
inputs:
  system:
    description: "The system for which to build the docker images for"
    default: "x86_64-linux"
  images:
    description: "List of Docker images to use as base name for tags"
    required: false
  push:
    description: "Push images to the Docker registry"
    required: false
    default: "true"
  username:
    description: "Username used to log against the Docker registry"
    required: true
  password:
    description: "Password or personal access token used to log against the Docker registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.images }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Install required cross-system tool
      if: "${{ inputs.system != 'x86_64-linux' }}"
      run: sudo apt-get install -y qemu-user-static
      shell: bash
    - uses: DeterminateSystems/nix-installer-action@v16
      with:
        extra-conf: |
          extra-platforms = ${{ inputs.system }}
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - name: Build the docker image pusher
      shell: bash
      env:
        RELEASE_VERSION: ${{ github.ref_name }}
      run: |
        nix build -L --impure .#packages.${{ inputs.system }}.push-docker-image
    - name: Push the docker image
      if: ${{ inputs.push }}
      env:
        DOCKER_IMAGE_TAGS: ${{ steps.meta.outputs.tags }}
      shell: bash
      run: |
        ./result
