name: Docker multi-arch manifest
description: "Create a multi-architecture manifest"
inputs:
  systems:
    description: "The systems for which to add support for, separated by a comma"
    required: true
  images:
    description: "List of Docker images to use as base name for tags"
    required: false
  push:
    description: "Push images to the Docker registry"
    required: false
    default: "true"
  username:
    description: "Username used to log against the Docker registry"
    required: true
  password:
    description: "Password or personal access token used to log against the Docker registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.images }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Create a multi-architecture manifest
      env:
        DOCKER_IMAGE_TAGS: ${{ steps.meta.outputs.tags }}
      shell: bash
      run: |
        for tag in $DOCKER_IMAGE_TAGS; do
          imgs=()
          for system in $( echo "${{ inputs.systems }}" | tr ',' ' ' ); do
            imgs+=("$tag-$system")
          done

          docker manifest create $tag ${imgs[*]}
        done
    - name: Push the docker image
      if: ${{ inputs.push }}
      env:
        DOCKER_IMAGE_TAGS: ${{ steps.meta.outputs.tags }}
      shell: bash
      run: |
        for tag in $DOCKER_IMAGE_TAGS; do
          docker manifest push $tag
        done
